author: Evan Briggs
email: evan.briggs@magichat.net
title: Magic Hat Brewing Company
url: "https://magichat.net"
include: [ _redirects]
whatsontap:
  - name: "9"
    tag: Not Quite Pale Ale
    abv: 5.1
    ibu: 20
    srm: 8
    untappd: https://untappd.com/b/magic-hat-brewing-company-9/3776
  - name: Barroom Hero
    tag: Pub Ale
    abv: 4.2
    ibu: 15
    srm: 30
    untappd:
  - name: Blind Faith
    tag: English Style IPA
    abv: 6.2
    ibu: 50
    srm: 9
    untappd:
  - name: Circus Boy
    tag: The Hefeweizen
    abv: 4.5
    ibu: 15
    srm: 6
    untappd:
  - name: Zirkus Boy
    tag: The Hefeweizen
    abv: 4.5
    ibu: 15
    srm: 6
    untappd:
  - name: Single Chair
    tag: The Golden Ale
    abv: 5.0
    ibu: 17
    srm: 3.5
    untappd:
  - name: TFG
    tag: A Rock Solid I.P.A
    abv: 6.6
    ibu: 66
    srm: 13
    untappd:
  - name: Elder Betty
    tag: ELDERBERRY WEISS
    abv: 5.5
    ibu: 13
    srm: 5.5
    untappd:
  - name: Big Hundo
    tag: Imperial IPA
    abv: 9.0
    ibu: 100
    srm: 5
  - name: Feast of Fools
    tag: STOUT BREWED WITH RASPBERRY
    abv: 7.4
    ibu: 28
    srm: 50
    untappd:
  - name: Elderberry Saison
    tag: Pilot Batch Saison
    abv: 5.8
    ibu: 30
    srm: 
    pilot: yes
    untappd:
  - name: Kittens on Parade
    tag: Pilot Batch Double IPA
    abv: 8.2
    ibu: 80
    srm: 
    pilot: yes
    untappd:
  - name: Tripel Chair
    tag: Pilot Batch Belgian Tripel
    abv: 9.1
    ibu: 20
    srm: 
    pilot: yes